rent_car_homepage:
    path:     /
    defaults: { _controller: RentCarBundle:Default:index }
rentcarbundle_contact:
    path:     /contact/
    defaults: { _controller: RentCarBundle:Contact:index}
rentcarbundle_cars:
    path:     /cars/
    defaults: { _controller: RentCarBundle:Cars:index}
rentcarbundle_car1:
    path:     /car1/
    defaults: { _controller: RentCarBundle:Car1:index}
rentcarbundle_car2:
    path:     /car2/
    defaults: { _controller: RentCarBundle:Car2:index}
rentcarbundle_car3:
    path:     /car3/
    defaults: { _controller: RentCarBundle:Car3:index}
rentcarbundle_car4:
    path:     /car4/
    defaults: { _controller: RentCarBundle:Car4:index}
rentcarbundle_car5:
    path:     /car5/
    defaults: { _controller: RentCarBundle:Car5:index}